# Generated by Django 3.0.8 on 2020-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('inf', 'Информатика'), ('othr', 'Другое')], max_length=4)),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=162)),
                ('max_people', models.IntegerField(default=5)),
                ('audio_works', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
