# Generated by Django 3.0.8 on 2020-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator',
            field=models.CharField(default='', max_length=162),
            preserve_default=False,
        ),
    ]
