# Generated by Django 3.0.8 on 2020-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_max_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('inf', 'Информатика')], default='math', max_length=4),
            preserve_default=False,
        ),
    ]
