# Generated by Django 3.0.8 on 2020-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20201209_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
